language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g npm@^5
install:
  - yarn install ---ignore-engines
script:
  - yarn prettier:run
  - git diff --exit-code ./src
  - yarn test:ci
  - yarn build
deploy:
  provider: npm
  email: iturgeon+npm@gmail.com
  api_key:
    secure: pSJyV23FFK0xL3N6Xl4kaVse4qlihtHVwkzYC+mHLQWa780eKQNv9OoWGDvuUoZi17Ivr9DVGsllaShRVVQxecT6hoXnRi01VBLCWm67ezEe1Tnhiv6DsHa1qtWeYjp31ig9/7A3+Kse/vuIJdW/A5EkHQFZT2UoXVwYerFFAZ101NUmHBQuvrNRVEDFxbduLKOGgksx4FIFx0miIs9XkEMqiMWDMKyxr0Sui0cTG/DDMd65QuUFiap5Bcz6FwB6saiGLSBS3YEuFAQI3ytazr4szERjWUTEkkUmglx/BNRIPmg/sAuMVFFxfBdzWih9LbTSP+vN8nknLmrCCUpJd/GZuYjFbDQ3IHbGvDUchmVeJnzG13GYCIhzKEC246Wo8y2jIsIFHUBPAqZpPdiU9op6Et4UuJIVLHGjvOm8hWl1BTJ3H7E8utPbmDGfwuMoqRCRagyvW7DT++NwwdwCLq2uMEbEKAGU1HWuOSYSuzFz8y8Hm6LvVXlUhLiq+dmkdGfLup4L6vENBr4wQkcIE960uC/D09cvAqsIuV9mX134Z6MK0GhdUaFFT/eARWk7DiHEuUpqStqcG0wrc85IXkVWa3Fi4lgGL5Q6GRg5xbysEoD4Q0XPpp3KdDrXnSvuHHrL0xy5MjZBfsYegP1mKYBYeHGWIaPJmD3ky2k78S0=
  on:
    tags: true
    repo: ucfopen/Materia-Server-Client-Assets
